
package com.example.springsoapclient.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PersonPortService", targetNamespace = "http://localhost:8080/hisoap", wsdlLocation = "http://localhost:8080/ws/personDefinition.wsdl")
public class PersonPortService
    extends Service
{

    private final static URL PERSONPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONPORTSERVICE_EXCEPTION;
    private final static QName PERSONPORTSERVICE_QNAME = new QName("http://localhost:8080/hisoap", "PersonPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/personDefinition.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONPORTSERVICE_WSDL_LOCATION = url;
        PERSONPORTSERVICE_EXCEPTION = e;
    }

    public PersonPortService() {
        super(__getWsdlLocation(), PERSONPORTSERVICE_QNAME);
    }

    public PersonPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONPORTSERVICE_QNAME, features);
    }

    public PersonPortService(URL wsdlLocation) {
        super(wsdlLocation, PERSONPORTSERVICE_QNAME);
    }

    public PersonPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONPORTSERVICE_QNAME, features);
    }

    public PersonPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonPort
     */
    @WebEndpoint(name = "PersonPortSoap11")
    public PersonPort getPersonPortSoap11() {
        return super.getPort(new QName("http://localhost:8080/hisoap", "PersonPortSoap11"), PersonPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonPort
     */
    @WebEndpoint(name = "PersonPortSoap11")
    public PersonPort getPersonPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/hisoap", "PersonPortSoap11"), PersonPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONPORTSERVICE_EXCEPTION!= null) {
            throw PERSONPORTSERVICE_EXCEPTION;
        }
        return PERSONPORTSERVICE_WSDL_LOCATION;
    }

}
