### GET TENANT ID
GET http://localhost:8080/tenant
X-TenantId: bulk

#############################
### Instruments Endpoints ###
#############################

###
GET http://localhost:8080/instrument
X-TenantId: one

###
GET http://localhost:8080/instrument/bass
X-TenantId: one

###
POST http://localhost:8080/instrument
Content-Type: application/json
X-TenantId: one

{
  "name": "ada",
  "type": "drums"
}


###
POST http://localhost:8080/instrument
Content-Type: application/json
X-TenantId: one

{
  "name": "telecaster",
  "type": "bass"
}