###
GET http://localhost:8080/free

###
GET http://localhost:8080/auth
Authorization: Bearer myBearerTokenFake


###
GET http://localhost:8080/api-content
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZSIsImlzcyI6Ik15IEFwcGxpY2F0aW9uIiwiZXhwIjoxNjk2MjA0NzQzfQ.v8D0oRSL7NkL75sFG9lY4HHZ9LpYrij7yctvUf-qhz8

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "me",
  "password": "myPassword"
}