###
GET http://localhost:8080/free

###
GET http://localhost:8080/auth
Authorization: Bearer myBearerTokenFake


###
GET http://localhost:8080/api-content
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZSIsImlzcyI6Ik15IEFwcGxpY2F0aW9uIiwiZXhwIjoxNjk2MTg5OTk5fQ.LReYImrfJvQQCG8fXJO2SN6obNLe_b0Ovp4oB6PHv5E

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "me",
  "password": "myPassword"
}